### ISSUE TITLE
Go test support

### ISSUE THREAD

**Issue by jesse-c** [uptech/alt#26]
Firstly, thank you for making this.

With alt 3.1.0, installed through Homebrew on macOS, no alternative files are being found for Go tests. E.g. if I have `main.go` and `main_test.go` (same directory), I expect the `_test.go` file to be found.

**Comment by drewdeponte** [comment]
I believe this fix was released with  v3.4.0.

**Comment by drewdeponte** [comment]
I verified this works in v3.4.0. Therefore, I am closing this issue.
