### ISSUE TITLE
Clarify what "alternate path" actually means

### ISSUE THREAD

**Issue by BenSandeen** [uptech/alt#28]
The readme should be more clear what "alternate path" means.  Is it the location of a duplicate file?  Is it a suggested place to put the file instead of its current location?  Or is it maybe something else?

**Comment by brandonpittman** [comment]
Yeah, it took me a moment to realize what was meant by "alternate". 🤔

**Comment by drewdeponte** [comment]
I have addressed this in the above commit. Therefore, I am closing this issue.
